### ISSUE TITLE
Chunks not rendering in 1 chunk render distance

### ISSUE THREAD

**Issue by catfoolyou** [PeytonPlayz595/Shadow-4.0#2]
If the render distance is set to one chunk, it will not render chunks close to the player. Setting the render distance to anything above 1 seems to fix this, however FPS drops horribly. The vanilla client gives better FPS than this, and I had all of Optifine's fast math and other optimisations turned on.

**Comment by PeytonPlayz595** [comment]
Are you on a Chromebook? People have been reporting issues with FPS drops and chunk loading on the latest commit, especially on Chromebooks, people seem to have no issue with it on Windows for some reason (as far as I know). Anyways, later tonight I'll try to go back and see if I can find what's in the commit that's causing the FPS drops and chunk issues. I think one issue for chunk loading is I've changed some `gluPerspective` calls in the `EntityRenderer` and `RenderGlobal` classes  to match Optifine because chunks along with custom skies would have this weird clipping issue with lower render distance chunks but I'll just make the sky not render and change the `gluPerspective` calls back to normal if the render distance is set to 1 chunk, all of that is not supposed to render anyways unless the render distance is set to 4 (8 for custom skies) or higher but I know most people are probably playing on Chromebook's and wouldn't be able to use it so I decided to make it render at a lower render distance, I've done some testing and it doesn't seem to affect performance, it just has some weird bugs that need to be worked out.

**Comment by PeytonPlayz595** [comment]
Be aware that this is not an "official" release, it is a beta version that is still being worked on and still has some bugs I'm trying to fix. I'll create an release on the GitHub page when I feel like the client is ready.

**Comment by PeytonPlayz595** [comment]
Oh also @catfoolyou don't use the offline download or web files from this GitHub, they are VERY outdated, I'll compile whenever I get a chance but for now use the offline download from the Discord server.

**Comment by catfoolyou** [comment]
I'm on a Windows laptop, using an offline download because I'm too lazy to run a single command to start an HTTP server. I'll check out the new downloads today, thanks.

**Comment by catfoolyou** [comment]
Also some pics of the bug and the lag spikes. It goes from 115 to 14 FPS, while I get a stable 80-100 FPS on vanilla desktop clients and on my 1.12 desktop runtime.
![Screenshot 2024-04-16 081218](https://github.com/PeytonPlayz595/Shadow-4.0/assets/95507639/71666a2c-6d6b-40cd-a568-9e9565373b96)
![Screenshot 2024-04-16 081133](https://github.com/PeytonPlayz595/Shadow-4.0/assets/95507639/1901c103-9a26-46a5-b103-b799bb819e11)

**Comment by PeytonPlayz595** [comment]
> Also some pics of the bug and the lag spikes. It goes from 115 to 14 FPS, while I get a stable 80-100 FPS on vanilla desktop clients and on my 1.12 desktop runtime. ![Screenshot 2024-04-16 081218](https://private-user-images.githubusercontent.com/95507639/322836881-71666a2c-6d6b-40cd-a568-9e9565373b96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzMDA4MTIsIm5iZiI6MTcxMzMwMDUxMiwicGF0aCI6Ii85NTUwNzYzOS8zMjI4MzY4ODEtNzE2NjZhMmMtNmQ2Yi00MGNkLWE1NjgtOWU5NTY1MzczYjk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDIwNDgzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzODBkMmY5ZTllNGM5MDg3NGM2ZTgzZmRhNGEwYWZkMzE0MzQ3OTJiNjg5NjA0MmNiZGJlNjJjMzAwZWJjMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bS0r5TpS7c2GgKclUV3Euhm1ehehnsX_n4SDDskMEy8) ![Screenshot 2024-04-16 081133](https://private-user-images.githubusercontent.com/95507639/322836886-1901c103-9a26-46a5-b103-b799bb819e11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzMDA4MTIsIm5iZiI6MTcxMzMwMDUxMiwicGF0aCI6Ii85NTUwNzYzOS8zMjI4MzY4ODYtMTkwMWMxMDMtOWEyNi00NmE1LWIxMDMtYjc5OWJiODE5ZTExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDIwNDgzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmZjA1MmE2ZmY5ZmY2MjZlNDZlMTQ4MWQxYjUxNTg3ZGUzODVkZDgwNzc3ODk2MjY0ZGI4YjY2MmU0M2JjNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i7e3f9t2gHDAwptbVDJd54VQAv3TpwGhBrIDdRqGfy0)

Yeah it turns out setting the thread priority in TeaVM causes MASSIVE lag spikes for some reason, I pushed a commit changing the singleplayer server thread priority, the TPS is slightly better but it causes a huge dip in FPS. The chunk loading issue's you're having in the screenshots above have been fixed in the latest version but I'll push a new commit in a few minutes changing the thread priority back to normal which should fix the lag spikes.

**Comment by PeytonPlayz595** [comment]
After doing some testing I have found that this is a bug that only occurs when fog it turned on, I fixed the bug with fog off but it still happens if the player has fog turned on

**Comment by PeytonPlayz595** [comment]
Just fixed it, I also changed the thread priority back to normal, I'm not sure if that is the reason for the lag spikes or not, I don't have any lag spikes, it runs just fine on my PC and Chromebook so idk.

**Comment by catfoolyou** [comment]
The chunk thing is still there with the latest version, lag is down though.

**Comment by PeytonPlayz595** [comment]
This has been fixed in the most recent version, there are still some issues with FPS but I think that has to do with Custom Items and Custom Colors, just turn them off and you should be fine, I'm working on a fix for it and should be released within a day or two.
